image: maven:3.3.9-jdk-8

build_staging:
  stage: build
  environment:
    name: dev
  script:
     - mvn clean verify
  artifacts:
    when: always
    name: "serenity"
    paths:
    - /builds/whiz-latam/myscouter/myscouter-qa-api/target/site/serenity/*
    expire_in: 24 h   
  only:
    - develop
